name: real-estate-app

services:
  demand-prediction:
    image: 957417441966.dkr.ecr.ap-south-1.amazonaws.com/real-estate-streamlit:latest
    container_name: real-estate
    environment:
      DAGSHUB_USER_TOKEN: "7194e08087f7cfb953d8913965a4c305ae5aa7b1"


    ports:
      - "80:8000"

    volumes:
      - /var/mlops/audit:/app/audit

    restart: unless-stopped
    
    networks:
      - real-estate-network

networks:
  real-estate-network:
    driver: bridge

   